backend:
  name: git-gateway
  branch: main   # or "master" depending on your GitHub repo

media_folder: "uploads"   # where images go in your repo
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
